export const STORAGE_KEY = {
  LAST_TRADE_LIST_SEARCH: "HOUSE_TRADE:LAST_TRADE_LIST_SEARCH",
  LAST_TRADE_LIST_ORDER: "HOUSE_TRADE:LAST_TRADE_LIST_ORDER",
  SAVED_REGIONS: "HOUSE_TRADE:SAVED_REGIONS",
  SAVED_APARTS: "HOUSE_TRADE:SAVED_APARTS",
} as const;
